# Generated by Django 5.2.1 on 2025-08-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=10)),
                ('telefone', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('descricao', models.TextField(max_length=255)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='core_imagens/%Y/%m')),
            ],
        ),
    ]
